/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* UART_1_SCB_IRQ */
    const cy_stc_sysint_t UART_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* Timer_int */
    const cy_stc_sysint_t Timer_int_cfg = {
        .intrSrc = (IRQn_Type)Timer_int__INTC_NUMBER,
        .intrPriority = Timer_int__INTC_CORTEXM4_PRIORITY
    };

    /* Timer2_int */
    const cy_stc_sysint_t Timer2_int_cfg = {
        .intrSrc = (IRQn_Type)Timer2_int__INTC_NUMBER,
        .intrPriority = Timer2_int__INTC_CORTEXM4_PRIORITY
    };

    /* Opto_detec */
    const cy_stc_sysint_t Opto_detec_cfg = {
        .intrSrc = (IRQn_Type)Opto_detec__INTC_NUMBER,
        .intrPriority = Opto_detec__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

