/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Trig_int */
#define Trig_int__INTC_CORTEXM4_ASSIGNED 1
#define Trig_int__INTC_CORTEXM4_PRIORITY 7u
#define Trig_int__INTC_NUMBER 91u
#define Trig_int_INTC_CORTEXM4_ASSIGNED 1
#define Trig_int_INTC_CORTEXM4_PRIORITY 7u
#define Trig_int_INTC_NUMBER 91u

/* Encoder_int */
#define Encoder_int__INTC_CORTEXM4_ASSIGNED 1
#define Encoder_int__INTC_CORTEXM4_PRIORITY 7u
#define Encoder_int__INTC_NUMBER 122u
#define Encoder_int_INTC_CORTEXM4_ASSIGNED 1
#define Encoder_int_INTC_CORTEXM4_PRIORITY 7u
#define Encoder_int_INTC_NUMBER 122u

/* Trig_end_int */
#define Trig_end_int__INTC_CORTEXM4_ASSIGNED 1
#define Trig_end_int__INTC_CORTEXM4_PRIORITY 7u
#define Trig_end_int__INTC_NUMBER 90u
#define Trig_end_int_INTC_CORTEXM4_ASSIGNED 1
#define Trig_end_int_INTC_CORTEXM4_PRIORITY 7u
#define Trig_end_int_INTC_NUMBER 90u

/* Opto_detec_int */
#define Opto_detec_int__INTC_CORTEXM4_ASSIGNED 1
#define Opto_detec_int__INTC_CORTEXM4_PRIORITY 7u
#define Opto_detec_int__INTC_NUMBER 123u
#define Opto_detec_int_INTC_CORTEXM4_ASSIGNED 1
#define Opto_detec_int_INTC_CORTEXM4_PRIORITY 7u
#define Opto_detec_int_INTC_NUMBER 123u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
