/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Boton_int */
#define Boton_int__INTC_CORTEXM4_ASSIGNED 1
#define Boton_int__INTC_CORTEXM4_PRIORITY 7u
#define Boton_int__INTC_NUMBER 122u
#define Boton_int_INTC_CORTEXM4_ASSIGNED 1
#define Boton_int_INTC_CORTEXM4_PRIORITY 7u
#define Boton_int_INTC_NUMBER 122u

/* Timer_int */
#define Timer_int__INTC_CORTEXM4_ASSIGNED 1
#define Timer_int__INTC_CORTEXM4_PRIORITY 7u
#define Timer_int__INTC_NUMBER 90u
#define Timer_int_INTC_CORTEXM4_ASSIGNED 1
#define Timer_int_INTC_CORTEXM4_PRIORITY 7u
#define Timer_int_INTC_NUMBER 90u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
