/*******************************************************************************
* File Name: cyfitter_sysint_cfg.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_CFG_H
#define INCLUDED_CYFITTER_SYSINT_CFG_H

#include "sysint/cy_sysint.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))
    #define UART_1_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t UART_1_SCB_IRQ_cfg;

    #define Debouncer_ovrflw_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Debouncer_ovrflw_int_cfg;

    #define Trig_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Trig_int_cfg;

    #define Trig_end_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Trig_end_int_cfg;

    #define Encoder_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Encoder_int_cfg;

    #define Opto_detec_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Opto_detec_int_cfg;

    #define SW0_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SW0_int_cfg;

    #define SW1_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SW1_int_cfg;

    #define SW2_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SW2_int_cfg;

    #define SW3_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SW3_int_cfg;

    #define SW4_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SW4_int_cfg;

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */


#endif /* INCLUDED_CYFITTER_SYSINT_CFG_H */
