/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* UART_1_SCB_IRQ */
    const cy_stc_sysint_t UART_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* Trig_int */
    const cy_stc_sysint_t Trig_int_cfg = {
        .intrSrc = (IRQn_Type)Trig_int__INTC_NUMBER,
        .intrPriority = Trig_int__INTC_CORTEXM4_PRIORITY
    };

    /* Trig_end_int */
    const cy_stc_sysint_t Trig_end_int_cfg = {
        .intrSrc = (IRQn_Type)Trig_end_int__INTC_NUMBER,
        .intrPriority = Trig_end_int__INTC_CORTEXM4_PRIORITY
    };

    /* Encoder_int */
    const cy_stc_sysint_t Encoder_int_cfg = {
        .intrSrc = (IRQn_Type)Encoder_int__INTC_NUMBER,
        .intrPriority = Encoder_int__INTC_CORTEXM4_PRIORITY
    };

    /* Opto_detec_int */
    const cy_stc_sysint_t Opto_detec_int_cfg = {
        .intrSrc = (IRQn_Type)Opto_detec_int__INTC_NUMBER,
        .intrPriority = Opto_detec_int__INTC_CORTEXM4_PRIORITY
    };

    /* SW0_int */
    const cy_stc_sysint_t SW0_int_cfg = {
        .intrSrc = (IRQn_Type)SW0_int__INTC_NUMBER,
        .intrPriority = SW0_int__INTC_CORTEXM4_PRIORITY
    };

    /* SW1_int */
    const cy_stc_sysint_t SW1_int_cfg = {
        .intrSrc = (IRQn_Type)SW1_int__INTC_NUMBER,
        .intrPriority = SW1_int__INTC_CORTEXM4_PRIORITY
    };

    /* SW2_int */
    const cy_stc_sysint_t SW2_int_cfg = {
        .intrSrc = (IRQn_Type)SW2_int__INTC_NUMBER,
        .intrPriority = SW2_int__INTC_CORTEXM4_PRIORITY
    };

    /* SW3_int */
    const cy_stc_sysint_t SW3_int_cfg = {
        .intrSrc = (IRQn_Type)SW3_int__INTC_NUMBER,
        .intrPriority = SW3_int__INTC_CORTEXM4_PRIORITY
    };

    /* SW4_int */
    const cy_stc_sysint_t SW4_int_cfg = {
        .intrSrc = (IRQn_Type)SW4_int__INTC_NUMBER,
        .intrPriority = SW4_int__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

